// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");

var content = "Some big amount of conent here that doesn't really say anything. It is here nonetheless, though";

var style = {
  borderStyle: "solid",
  borderWidth: "1px",
  marginBottom: "2px",
  paddingRight: "3px",
  paddingBottom: "1px",
  paddingLeft: "3px"
};

function App$Post(Props) {
  var id = Props.id;
  var title = Props.title;
  return React.createElement("div", {
              className: "post",
              id: String(id),
              style: style
            }, React.createElement("span", undefined, React.createElement("strong", undefined, "#" + String(id)), React.createElement("center", undefined, React.createElement("h2", undefined, title))), React.createElement("div", {
                  className: "post-content"
                }, content));
}

var Post = /* module */[
  /* content */content,
  /* style */style,
  /* make */App$Post
];

function App(Props) {
  var header = Props.header;
  return React.createElement("div", undefined, React.createElement("h1", undefined, React.createElement("center", undefined, header)), React.createElement("hr", undefined), $$Array.init(8, (function (i) {
                    return React.createElement(App$Post, {
                                id: i,
                                title: "Some Title",
                                key: String(i)
                              });
                  })));
}

var make = App;

exports.Post = Post;
exports.make = make;
/* react Not a pure module */
