// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var style = {
  borderStyle: "solid",
  borderWidth: "1px",
  marginBottom: "2px",
  paddingRight: "3px",
  paddingBottom: "1px",
  paddingLeft: "3px"
};

function Post(Props) {
  var id = Props.id;
  var title = Props.title;
  var content = Props.content;
  return React.createElement("div", {
              className: "post",
              id: String(id),
              style: style
            }, React.createElement("span", undefined, React.createElement("strong", undefined, "#" + String(id)), React.createElement("center", undefined, React.createElement("h2", undefined, title))), React.createElement("div", {
                  className: "post-content"
                }, content));
}

var make = Post;

exports.style = style;
exports.make = make;
/* react Not a pure module */
